// CurrentAddress
export const UPDATE_CURRENT_ADDRESS = 'UPDATE_CURRENT_ADDRESS'
export const UPDATE_CURRENT_LAT = 'UPDATE_CURRENT_LAT'
export const UPDATE_CURRENT_LNG = 'UPDATE_CURRENT_LNG'
export const CURRENT_TAG = 'CURRENT_TAG'
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
